name: JonCsWebServer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#permissions:
#  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            output_name: WebServer.x86_64
            output_name_lite: WebServer_lite.x86_64
          - rid: linux-arm
            output_name: WebServer.arm
            output_name_lite: WebServer_lite.arm
          - rid: linux-arm64
            output_name: WebServer.aarch64
            output_name_lite: WebServer_lite.aarch64
          - rid: win-x86
            output_name: WebServer.exe
            output_name_lite: WebServer_lite.exe
          - rid: win-x64
            output_name: WebServer64.exe
            output_name_lite: WebServer64_lite.exe
          - rid: win-arm64
            output_name: WebServer_arm64.exe
            output_name_lite: WebServer_lite_arm64.exe
          - rid: osx-x64
            output_name: WebServer.osx-x64
            output_name_lite: WebServer_lite.osx-x64
          - rid: osx-arm64
            output_name: WebServer.osx-arm64
            output_name_lite: WebServer_lite.osx-arm64
# Android build not supported by AspNetCore
#          - rid: android-arm64 
#            output_name: WebServer.android
#            outout_name_lite: WebServer_lite.android
# Windows 32-bit arm not buildable:
#           - rid: win-arm
#            output_name: WebServer_arm.exe
#            output_name_lite: WebServer_lite_arm.exe

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore
      run: dotnet restore WebServer/WebServer.csproj

    #
    # NORMAL BUILD
    #
    - name: Publish ${{ matrix.rid }}
      run: >
        dotnet publish WebServer/WebServer.csproj
        -c Release
        -r ${{ matrix.rid }}
        --self-contained true
        -p:PublishSingleFile=true
        -o ./publish/${{ matrix.rid }}

    - name: Publish ${{ matrix.rid }} trimmed
      run: >
        dotnet publish WebServer/WebServer.csproj
        -c Release
        -r ${{ matrix.rid }}
        --self-contained true
        -p:PublishSingleFile=true
        -p:PublishTrimmed=true
        -p:EnableCompressionInSingleFile=true
        -p:InvariantGlobalization=true
        -o ./publish/${{ matrix.rid }}_lite

    #
    # ReadyToRun BUILD
    #
    - name: Publish ${{ matrix.rid }} ReadyToRun
      run: >
        dotnet publish WebServer/WebServer.csproj
        -c Release
        -r ${{ matrix.rid }}
        --self-contained true
        -p:PublishSingleFile=true
        -p:PublishReadyToRun=true
        -p:EnableCompressionInSingleFile=true
        -p:InvariantGlobalization=true
        -o ./publish/${{ matrix.rid }}_ReadyToRun

    - name: Rename outputs
      run: |
        # Non-trimmed
        src_exe="./publish/${{ matrix.rid }}/WebServer"
        [ -f "${src_exe}.exe" ] && src_exe="${src_exe}.exe"
        mv "$src_exe" "./publish/${{ matrix.rid }}/${{ matrix.output_name }}" || true

        # Trimmed
        src_lite="./publish/${{ matrix.rid }}_lite/WebServer"
        [ -f "${src_lite}.exe" ] && src_lite="${src_lite}.exe"
        mv "$src_lite" "./publish/${{ matrix.rid }}_lite/${{ matrix.output_name_lite }}" || true

        # ReadyToRun
        src_exe="./publish/${{ matrix.rid }}_ReadyToRun/WebServer"
        [ -f "${src_exe}_ReadyToRun.exe" ] && src_exe="${src_exe}_ReadyToRun.exe"
        mv "$src_exe" "./publish/${{ matrix.rid }}_ReadyToRun/${{ matrix.output_name }}_ReadyToRun" || true

    - name: Upload ${{ matrix.rid }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: ./publish/${{ matrix.rid }}/${{ matrix.output_name }}

    - name: Upload ${{ matrix.rid }} trimmed
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name_lite }}
        path: ./publish/${{ matrix.rid }}_lite/${{ matrix.output_name_lite }}

    - name: Upload ${{ matrix.rid }} ReadyToRun
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}_ReadyToRun
        path: ./publish/${{ matrix.rid }}_ReadyToRun/${{ matrix.output_name }}_ReadyToRun

  prerelease:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./release_files

    - name: Flatten artifacts
      shell: bash
      run: |
        mkdir ./final

        find ./release_files -type f -exec cp {} ./final/ \;

    - name: Create Pre-Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        prerelease: true
        generate_release_notes: true
        files: ./final/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
